
yields:
  setupCampaignDataSet: V12_CAMPAIGN
  mappings:
    France:
      -
        processVariable: T_CRITERE_FRA
        dataSet: V12_CRITERE_FRA
        ifModel: #empty matches all
      -
        processVariable: T_REF_FRA
        dataSet: V12_REF_FRA
        ifModel:
      -
        processVariable: T_SCORE_FRA
        dataSet: V12_SCORE_FRA
        ifModel:
      -
        processVariable: T_SCORE_VAR_FRA
        dataSet: V12_SCORE_VAR_FRA
        ifModel:
      -
        processVariable: T_MONITORING_FRAA0014V00
        dataSet: V12_MONITORING_FRAA0014V00
        ifModel: FRAA0014V00
      -
        processVariable: T_MONITORING_FRAB0001V00
        dataSet: V12_MONITORING_FRAB0001V00
        ifModel: FRAB0001V00
    Belgium:
      -
        processVariable: T_CRITERE_BEL
        dataSet: V12_CRITERE_BEL
        ifModel:
      -
        processVariable: T_REF_BEL
        dataSet: V12_REF_BEL
        ifModel:
      -
        processVariable: T_SCORE_BEL
        dataSet: V12_SCORE_BEL
        ifModel:
      -
        processVariable: T_SCORE_VAR_BEL
        dataSet: V12_SCORE_VAR_BEL
        ifModel:
      -
        processVariable: T_MONITORING_BEL
        dataSet: V12_MONITORING_BELA0014V00
        ifModel: BELA0014V00
  dataChecks:
    France:
      stageType: Derivation
      dataSet: V12_SCORE_ANALYSIS_FRA
    Belgium:
      stageType: Derivation
      dataSet: V12_SCORE_ANALYSIS_BEL
  performanceChecks:
    France:
      stageType: Analysis
      dataSet: V12_FRAB0001V00_SCORE_ANALYSIS
    Belgium:
      stageType: Analysis
      dataSet: V12_BELA0014V00_SCORE_ANALYSIS
