
yields:
  setupCampaignDataSet: T_CAMPAIGN
  mappings:
    France:
      -
        processVariable: T_CRITERE_FRA
        dataSet: T_CRITERE_FRA
        ifModel: #empty matches all
      -
        processVariable: T_REF_FRA
        dataSet: T_REF_FRA
        ifModel:
      -
        processVariable: T_SCORE_FRA
        dataSet: T_SCORE_FRA
        ifModel:
      -
        processVariable: T_SCORE_VAR_FRA
        dataSet: T_SCORE_VAR_FRA
        ifModel:
      -
        processVariable: T_MONITORING_FRAA0014V00
        dataSet: T_MONITORING_FRAA0014V00
        ifModel: FRAA0014V00
      -
        processVariable: T_MONITORING_FRAB0001V00
        dataSet: T_MONITORING_FRAB0001V00
        ifModel: FRAB0001V00
    Belgium:
      -
        processVariable: T_CRITERE_BEL
        dataSet: T_CRITERE_BEL
        ifModel:
      -
        processVariable: T_REF_BEL
        dataSet: T_REF_BEL
        ifModel:
      -
        processVariable: T_SCORE_BEL
        dataSet: T_SCORE_BEL
        ifModel:
      -
        processVariable: T_SCORE_VAR_BEL
        dataSet: T_SCORE_VAR_BEL
        ifModel:
      -
        processVariable: T_MONITORING_BEL
        dataSet: T_MONITORING_BELA0014V00
        ifModel: BELA0014V00
  dataChecks:
    France:
      stageType: Derivation
      dataSet: T_SCORE_ANALYSIS_FRA
    Belgium:
      stageType: Derivation
      dataSet: T_SCORE_ANALYSIS_BEL
  performanceChecks:
    France:
      -
        stageType: Analysis
        dataSet: T_FRAA0014V00_SCORE_ANALYSIS
        ifModel: FRAA0014V00
      -
        stageType: Analysis
        dataSet: T_FRAB0001V00_SCORE_ANALYSIS
        ifModel: FRAB0001V00
    Belgium:
      -
        stageType: Analysis
        dataSet: T_BELA0014V00_SCORE_ANALYSIS
        ifModel:
