
yields:
  setupCampaignDataSet: T_CAMPAIGN
  mappings:
    Belgium:
      -
        processVariable: demodata
        dataSet: demodata
        ifModel:
  dataChecks:
    Belgium:
      stageType: Derivation
      dataSet: demo_outlier
  performanceChecks:
    Belgium:
      -
        stageType: Analysis
        dataSet: demo_validation
        ifModel:
