
yields:
  setupCampaignDataSet: T_CAMPAIGN
  mappings:
    Belgium:
      -
        processVariable: demodata
        dataSet: CreditCardDefault
        ifModel:
  dataChecks:
    Belgium:
#      stageType: Derivation
      stageType: Training
      dataSet: ppnr_outlier
  performanceChecks:
    Belgium:
      -
        stageType: Analysis
        dataSet: ppnr_modelvalidation
        ifModel:
